# Import Necessary Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

This code imports essential Python libraries: `numpy` for numerical operations, `pandas` for data manipulation, `matplotlib.pyplot` for plotting, and `seaborn` for advanced visualizations. These libraries are fundamental for data analysis tasks.

## Load Data

In [ ]:
store=pd.read_csv("./drive/MyDrive/4-googleplaystore.csv")
store

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

This code loads the dataset from the specified CSV file ('./drive/MyDrive/4-googleplaystore.csv') into a pandas DataFrame named `store` and then displays the entire DataFrame. This allows for an initial inspection of the raw data.

## Check Data Shape

In [ ]:
store.shape

(10841, 13)

This code displays the shape of the `store` DataFrame, which indicates the number of rows (entries/apps) and columns (features) in the dataset. This is a quick way to understand the size of the dataset.

## Display Data Information

In [ ]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

This code prints a concise summary of the `store` DataFrame, including the column names, their data types (`Dtype`), the number of non-null values (`Non-Null Count`), and memory usage. This helps in understanding the data types and identifying columns with missing values.

## Check for Missing Values

In [ ]:
store.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

This code calculates and displays the count of missing (null) values for each column in the `store` DataFrame. It helps to quickly identify which columns have missing data and how many, informing subsequent data cleaning steps.

## Handle Missing Ratings

In [ ]:
store['Rating'] = store['Rating'].fillna(0)

This code fills any missing values (NaN) in the 'Rating' column of the `store` DataFrame with `0`. This is a common strategy to handle missing numerical ratings, treating them as a 'no rating' or a minimum rating.

## Handle Missing Current Version

In [ ]:
store['Current Ver'] = store['Current Ver'].fillna('NA')

This code fills any missing values (NaN) in the 'Current Ver' column of the `store` DataFrame with the string 'NA'. This handles missing version information by explicitly marking it as not available.

## Handle Missing Android Version

In [ ]:
store['Android Ver'] = store['Android Ver' ].fillna('NA')

This code fills any missing values (NaN) in the 'Android Ver' column of the `store` DataFrame with the string 'NA'. This handles missing Android version information by explicitly marking it as not available.

This code fills any missing values (NaN) in the 'Content Rating' column of the `store` DataFrame with the string 'NA'. This ensures consistency in how missing content rating information is represented.

## Handle Missing Content Rating

In [ ]:
store['Content Rating'] = store['Content Rating'].fillna('NA')

## Identify Problematic 'Installs' Entry

In [ ]:
store.loc[store['Installs']=='Free']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NA,"February 11, 2018",1.0.19,4.0 and up,NA

This code identifies and displays rows in the `store` DataFrame where the 'Installs' column contains the string 'Free'. This is used to pinpoint data entry errors where a categorical value like 'Free' has appeared in a numerical column.

## Remove Problematic Row

In [ ]:
#deleting row
store.drop(index=10472, inplace=True)

This code deletes the row at index `10472` from the `store` DataFrame. The `inplace=True` argument ensures that the modification is applied directly to the DataFrame. This specific row was identified in the previous step as containing erroneous 'Installs' data.

## Count Unique Apps

In [ ]:
store.App.nunique()

9659

This code calculates and displays the number of unique applications ('App') in the `store` DataFrame. It helps understand the diversity of apps in the dataset after cleaning.

## Clean 'Installs' Column

In [ ]:
store['Installs'] = store['Installs'].str.replace('+','',regex=False).str.replace(',','',regex=False)

This code cleans the 'Installs' column by removing '+' and ',' characters from the string values. This prepares the 'Installs' column for conversion to a numerical data type by removing non-numeric characters.

## Display Cleaned Data Head

In [ ]:
store.head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

This code displays the first 5 rows of the `store` DataFrame after the 'Installs' column has been cleaned. It allows for a quick visual check of the changes made.

## Descriptive Statistics for Rating

In [ ]:
store.describe()

             Rating
count  10840.000000
mean       3.621771
std        1.514563
min        0.000000
25%        3.700000
50%        4.200000
75%        4.500000
max        5.000000

This code generates descriptive statistics for all numerical columns in the `store` DataFrame. By default, with `Rating` being the only numeric column after the cleaning, it provides statistics like count, mean, standard deviation, min, max, and quartiles for the 'Rating' column.

## Convert 'Installs' to Integer

In [ ]:
store['Installs'].astype(int)

0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs, Length: 10840, dtype: int64

This code attempts to convert the 'Installs' column to an integer data type. The `astype(int)` method is used for this conversion, making the 'Installs' column suitable for numerical operations. Note that this operation is not assigned back to the DataFrame.

## Display Updated Data Information

In [ ]:
store.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10840 non-null  object
 2   Rating          10840 non-null  float64
 3   Reviews         10840 non-null  object
 4   Size            10840 non-null  object
 5   Installs        10840 non-null  object
 6   Type            10839 non-null  object
 7   Price           10840 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10840 non-null  object
 11  Current Ver     10840 non-null  object
 12  Android Ver     10840 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.4+ MB

This code prints a concise summary of the `store` DataFrame, including column names, their data types, and non-null counts after previous cleaning and type conversion attempts. This helps to verify the current state of the data types and missing values.

## Descriptive Statistics for 'Installs'

In [ ]:
store['Installs'].describe()

count       10840
unique         20
top       1000000
freq         1579
Name: Installs, dtype: object

This code generates descriptive statistics specifically for the 'Installs' column. Since 'Installs' is still of object type (string) in the DataFrame, it provides statistics relevant to categorical data, such as count, number of unique values, the most frequent value (`top`), and its frequency (`freq`).

## Clean 'Price' Column

In [ ]:
store['Price'] = store['Price'].str.replace('$','')

This code cleans the 'Price' column by removing the '$' character from the string values. This is a crucial step to prepare the 'Price' column for conversion into a numerical data type.

## Convert 'Price' to Float

In [ ]:
store['Price'].astype(float)

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
10836    0.0
10837    0.0
10838    0.0
10839    0.0
10840    0.0
Name: Price, Length: 10840, dtype: float64

This code attempts to convert the 'Price' column to a floating-point number data type. The `astype(float)` method is used for this conversion, enabling numerical calculations on the prices. Note that this operation is not assigned back to the DataFrame.

## Get Max Price

In [ ]:
store['Price'].max()

'9.99'

This code finds and displays the maximum value in the 'Price' column. Since the 'Price' column is still of object type (string) and contains strings after the '$' removal, this will return the lexicographically largest string, which might not be the numerically largest price.

## Display 'Price' Column Info

In [ ]:
store['Price'].info()

<class 'pandas.core.series.Series'>
Index: 10840 entries, 0 to 10840
Series name: Price
Non-Null Count  Dtype
--------------  -----
10840 non-null  object
dtypes: object(1)
memory usage: 427.4+ KB

This code prints a concise summary of the 'Price' column, including its data type, non-null count, and memory usage. This helps verify the current state of the 'Price' column, indicating it's still an object (string) type.

## Find Apps with Price '1.00'

In [ ]:
store.loc[store['Price']== '1.00']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2265,Arrhythmias and Dysrhythmias,MEDICAL,0.0,3,24M,500,Paid,1.00,Everyone,Medical,"January 24, 2016",1.0,4.2 and up
9026,PORTABLE SOCCER DX,SPORTS,4.4,552,1.6M,5000,Paid,1.00,Everyone,Sports,"June 19, 2018",3.4,2.2 and up
10460,Wi-Fi Rabbit Unlock Key,TOOLS,4.5,142,26k,5000,Paid,1.00,Everyone,Tools,"June 26, 2011",1.0.0,2.1 and up

This code identifies and displays rows in the `store` DataFrame where the 'Price' column has a value exactly equal to the string '1.00'. This allows for inspection of apps that are priced at exactly one unit (e.g., $1.00).

## Descriptive Statistics for 'Price'

In [ ]:
store['Price'].describe()

count     10840
unique       92
top           0
freq      10040
Name: Price, dtype: object

This code generates descriptive statistics for the 'Price' column. Since 'Price' is still of object type (string), it provides statistics relevant to categorical data, such as count, number of unique values, the most frequent value (`top`), and its frequency (`freq`).

## Get Max Price (again)

In [ ]:
store["Price"].max()

'9.99'

This code finds and displays the maximum value in the 'Price' column. Similar to a previous check, since the 'Price' column is still of object type (string), this returns the lexicographically largest string among the prices, which is '9.99'.

## Group Installs by Category

In [ ]:
store.groupby('Category')['Installs'].value_counts()

Category        Installs
ART_AND_DESIGN  100000      19
                10000       11
                50000        6
                500000       6
                10000000     5
                            ..
WEATHER         10000        4
                500          3
                10           2
                5000         1
                50000        1
Name: count, Length: 514, dtype: int64

This code groups the `store` DataFrame by 'Category' and then counts the occurrences of each unique 'Installs' value within each category. This helps in understanding the distribution of installation ranges across different app categories.

## Find App with Highest Reviews

In [ ]:
Highest_reviews = store.loc[store['Reviews'].idxmax()]
Highest_reviews

App               GollerCepte Live Score
Category                          SPORTS
Rating                               4.2
Reviews                             9992
Size                                 31M
Installs                         1000000
Type                                Free
Price                                  0
Content Rating                  Everyone
Genres                            Sports
Last Updated                May 23, 2018
Current Ver                          6.5
Android Ver                   4.1 and up
Name: 2989, dtype: object

This code identifies and displays the row corresponding to the app with the highest number of reviews. It uses `idxmax()` on the 'Reviews' column to find the index of the maximum value and then retrieves that entire row from the DataFrame.

## Bin 'Rating' Column

In [ ]:
rating_bin = pd.cut(store['Rating'],bins=[-0.001, 1, 2, 3, 4, 5],labels = ['very Bad','Bad','average','Good','Very Good'])
rating_bin

0        Very Good
1             Good
2        Very Good
3        Very Good
4        Very Good
           ...
10836    Very Good
10837    Very Good
10838     very Bad
10839    Very Good
10840    Very Good
Name: Rating, Length: 10840, dtype: category
Categories (5, object): ['very Bad' < 'Bad' < 'average' < 'Good' < 'Very Good']

This code categorizes the 'Rating' column into bins with labels: 'very Bad', 'Bad', 'average', 'Good', and 'Very Good'. The `pd.cut()` function is used to create these discrete bins based on the specified intervals, providing a categorical representation of the ratings.

## Display 'Reviews' Column Info

In [ ]:
store['Reviews'].info()

<class 'pandas.core.series.Series'>
Index: 10840 entries, 0 to 10840
Series name: Reviews
Non-Null Count  Dtype
--------------  -----
10840 non-null  object
dtypes: object(1)
memory usage: 427.4+ KB

This code prints a concise summary of the 'Reviews' column, including its data type, non-null count, and memory usage. This helps verify the current state of the 'Reviews' column, indicating it's still an object (string) type.

## Convert 'Reviews' to Integer

In [ ]:
store['Reviews'].astype(int)

0           159
1           967
2         87510
3        215644
4           967
          ...
10836        38
10837         4
10838         3
10839       114
10840    398307
Name: Reviews, Length: 10840, dtype: int64

This code attempts to convert the 'Reviews' column to an integer data type. The `astype(int)` method is used for this conversion, which would allow for numerical operations on review counts. Note that this operation is not assigned back to the DataFrame.

## Replace '3.0M' in Reviews (Note: This operation was not assigned back to the column)

In [ ]:
store['Reviews'].str.replace('3.0M','300,00,00,000')

0           159
1           967
2         87510
3        215644
4           967
          ...
10836        38
10837         4
10838         3
10839       114
10840    398307
Name: Reviews, Length: 10840, dtype: object

This code attempts to replace the string '3.0M' with '300,00,00,000' in the 'Reviews' column. This suggests an attempt to standardize large number representations, but the result of this `str.replace` operation is not assigned back to the column, so the DataFrame itself remains unchanged.

## Get Max Reviews

In [ ]:
store['Reviews'].max()

'9992'

This code finds and displays the maximum value in the 'Reviews' column. Since the 'Reviews' column is still of object type (string), this returns the lexicographically largest string among the review counts, which is '9992'.

## Display Column Names

In [ ]:
store.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

This code displays the names of all columns in the `store` DataFrame. This provides a clear overview of the features available in the dataset.